version: 2

defaults: &defaults
  docker:
      - image: circleci/node:9.8
  working_directory: ~/src

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/src
          paths:
            - node_modules

  test:
    setup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/dir
      - run: npm test
    
  build-deploy:
    setup:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/dir
      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2
  setup-and-test:
    jobs: 
      - setup
      - test:
          requires:
            - setup
  
  

