version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:9.8
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:9.8
    steps:
      - run: npm test
    
  build-deploy:
    docker:
      - image: circleci/node:9.8
    working_directory: ~/src
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2
  setup-and-test:
    jobs: 
      - setup
      - test
  
  

